### ISSUE TITLE
not working on MAC + sublime build 3103

### ISSUE THREAD

**Issue by jeroendesloovere** [naomichi-y/php_syntax_checker#13]
When saving a file with a syntax error in,
nothing happens...?

**Comment by lucianocn** [comment]
+1

**Comment by JamesNock** [comment]
Same problem in build 3114

**Comment by Razoxane** [comment]
Same problem in build 3126.

**Comment by naomichi-y** [comment]
This problem was fixed. Please use the latest version.
https://github.com/naomichi-y/php_syntax_checker/commit/b265e06f5bdc17a09af6a28c149ade4be600fb20
