### ISSUE TITLE
Issue about checking file containing space characters

### ISSUE THREAD

**Issue by sovoboys** [naomichi-y/php_syntax_checker#14]
(Sorry for my English.)

I've found that PHP Syntax Checker doesn't display any error message when I save file to directory containing space characters (e.g. D:\foo bar\app.php)

My workaround is to edit the phpSyntaxChecker.py @ line 10
from this
`command_line = self.EXECUTE_COMMAND + " " + file_path`

to this
`command_line = self.EXECUTE_COMMAND + " \"" + file_path + "\""`

and it works.

(my env)
PHP Syntax Checker Version: 2015.04.17.10.02.28
Sublime Text Version: 2.0.2
OS: Windows 7

**Comment by naomichi-y** [comment]
fixed this problem. thanks for feedback.

**Comment by tylernathanreed** [comment]
@naomichi-y This fix for this has caused this package to stop working for me.

If I use the pre-commit version:
`command_line = self.EXECUTE_COMMAND + " " + file_path`

It works just fine.

If I use the suggested version:
`command_line = self.EXECUTE_COMMAND + " \"" + file_path + "\""`

It works just fine.

However, if I use the committed version:
`command_line = self.EXECUTE_COMMAND + " '" + file_path + "'"`

It doesn't work at all.

I'm not sure why the committed version doesn't work, but I'll let you figure that one out.

**Comment by naomichi-y** [comment]
@tylernathanreed
Fixed problem. how is it?

https://github.com/naomichi-y/php_syntax_checker/commit/aa50a0fdeee42035ab5565eb71f3a36ed2d785f2

**Comment by tylernathanreed** [comment]
@naomichi-y Works perfectly. Thanks!
