### ISSUE TITLE
Does not work on sublime 3 (Build 3126) on macOS Sierra

### ISSUE THREAD

**Issue by yukari1414** [naomichi-y/php_syntax_checker#15]

**Comment by andrearufo** [comment]
+1

**Comment by Nomia** [comment]
+1

**Comment by naomichi-y** [comment]
This problem was fixed. Please use the latest version.

https://github.com/naomichi-y/php_syntax_checker/commit/b265e06f5bdc17a09af6a28c149ade4be600fb20
