### ISSUE TITLE
support for ST3

### ISSUE THREAD

**Issue by sandipp** [naomichi-y/php_syntax_checker#6]
any news about support for ST3 ?

**Comment by dsposito** [comment]
:+1:

**Comment by sandipp** [comment]
Thank you @naomichi-y for adding support for ST3.
But I've question that how can I install it in ST3?

**Comment by naomichi-y** [comment]
just has committed. im waiting for merge.
https://github.com/wbond/package_control_channel/pull/4296

**Comment by naomichi-y** [comment]
or, you can install by copying source.

e.g (mac)
$ git clone https://github.com/naomichi-y/php_syntax_checker.git
$ cp -Rf ~/Projects/php_syntax_checker "/Users/{account}/Library/Application Support/Sublime Text 3/Packages"
