### ISSUE TITLE
Use syntax rather than file extension for detecting PHP files?

### ISSUE THREAD

**Issue by erwinw** [naomichi-y/php_syntax_checker#8]
Perhaps it would be possible to use the file's syntax rather than the extension to detect PHP files (or a combination)? To get the file's syntax, use `view.settings().get('syntax')` - for PHP the standard syntax file is 'Packages/PHP/PHP.tmLanguage'. This way it's easier to use the plugin with PHP syntaxed files that have a different extension!

**Comment by naomichi-y** [comment]
:+1:

**Comment by erwinw** [comment]
Glad you liked it! :-)
